def sat(li: List[str]):
    return sum([1 for i in li if ord(i) % 3 == 2]) == 0

def sol():
    return [i for i in [chr(i) for i in range(32, 127)] if ord(i) % 3 == 2]

# The function 'sat' is already defined by the user. It checks if a list contains only lowercase letters.
# If it does, it returns True. Otherwise, it returns False.
# Here, the list is generated by mapping the ASCII values of the characters to their corresponding characters.
# This list is then filtered to only include the characters that have an ASCII value that is a multiple of 3.
# Finally, the sum of this list is checked to be 0, which means that the list contains no multiples of 3.
# If it does, the list is returned; otherwise, the function returns an empty list.

assert sat(sol())

if __name__ == "__main__":
    assert sat(sol())
